apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-auth-config
  namespace: default
data:
  AUTH_SERVICE_URL: "todo-auth-service:7000"
  AUTH_RPC_SERVICE_URL: "todo-auth-service:50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-auth-deployment
  labels:
    app: todo
    component: todo-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      component: todo-auth
  template:
    metadata:
      labels:
        component: todo-auth
    spec:
      containers:
        - name: todo-auth-pod
          image: dreambo8563docker/todo-auth:v13
          env:
            - name: JAEGER_SERVICE_NAME
              value: todo-auth-service
          ports:
            - containerPort: 7000
            - containerPort: 50051
          volumeMounts:
            - mountPath: /k8slog
              name: k8slog
          envFrom:
            - configMapRef:
                name: jaeger-configuration
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7000
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: k8slog
          hostPath:
            path: /Users/vincent/Documents/Golang/logs
            type: DirectoryOrCreate
---
kind: Service
apiVersion: v1
metadata:
  name: todo-auth-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: todo-auth
  ports:
    - name: http
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: rpc
      protocol: TCP
      port: 50051
      targetPort: 50051
