apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-auth-deployment
  labels:
    app: todo
    component: todo-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      component: todo-auth
  template:
    metadata:
      labels:
        component: todo-auth
    spec:
      containers:
        - name: component
          image: dreambo8563docker/todo-auth:v2
          ports:
            - containerPort: 7000
          volumeMounts:
            - mountPath: /k8slog
              name: k8slog
      volumes:
        - name: k8slog
          hostPath:
            path: /Users/vincent/Documents/Golang/logs
            type: DirectoryOrCreate
